[package]
name = "git-dep"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
camino = { version = "1.1.9", features = ["serde"] }
clap = { version = "4.5.23", features = ["cargo", "unstable-ext"] }
clap_complete = { version = "4.5.40", features = ["unstable-dynamic"] }
indexmap = { version = "2.7.0", features = ["serde"] }
itertools = "0.14.0"
petgraph = "0.7.0"
rand = "0.8.5"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
